### ISSUE TITLE
implement /me suppport from irc to slack

### ISSUE THREAD

**Issue by gnowxilef** [ocf/slackbridge#2]

**Comment by jvperrin** [comment]
The past bridge did this, it just involves handling a different message type:

https://github.com/ekmartin/slack-irc/blob/6eaa3a28d290ed290cec16424a9c1d3ad4643ed7/lib/bot.js#L227-L229

I do think we should take a different approach, since seeing `Action: blah` was kinda weird, maybe we can just put it in italics like `/me` does in Slack?

**Comment by gnowxilef** [comment]
+1 to italics
