### ISSUE TITLE
Ensure channels are automatically formatted for hotlinking from IRC -> Slack

### ISSUE THREAD

**Issue by redplanks** [ocf/slackbridge#37]
A subset of #23.

Currently, Slack only autolinks channels formatted like 
`<#C1WSVQAKD|rebuild-spam>`
and not channels formatted like
`#rebuild-spam`.

A regex and a dictionary that maps between channel names and UIDs would probably fix it.

**Comment by kkuehler** [comment]
Yep, I think @jvperrin noted that he wrote the code for this and just has to commit it.

**Comment by jvperrin** [comment]
I haven't actually done this direction of mapping yet, I've done the mapping where when Slack sends it, it formats it to not look like `<#C1WSVQAKD|rebuild-spam>`, but instead display like `#rebuild-spam`. Mapping the other direction shouldn't be too terrible, since there's already a name to UID dictionary mapping available, and would be pretty useful, like for channel topics, for instance.

**Comment by dkess** [comment]
Is this resolved? I haven't noticed it being a problem in a while.

**Comment by redplanks** [comment]
It looks fixed, though I'm not sure which PR fixed it.
