### ISSUE TITLE
integrate fully with slack

### ISSUE THREAD

**Issue by gnowxilef** [ocf/slackbridge#84]
the bridge currently does not fully create a user in slack. tanya (or updating slackbridge/any equivalent app) solves this issue. see https://github.com/nolanlum/tanya

also created https://github.com/ocf/ircbot/issues/145 to integrate ircbot fully.

**Comment by jvperrin** [comment]
It does though, it makes a user named `@irc-bridge`, or am I misunderstanding what you want here? I don't think we can feasibly create a Slack user per IRC user that joins since we'd need to make a new Slack user for each person in some dynamic way that I don't believe Slack has an API for.

**Comment by cg505** [comment]
I may be misunderstanding, but at a glance it looks like tanya is designed to create a local irc server that a slack user can use to connect to slack (instead of using the normal slack app). This is not really what we want, as we would have to run separate servers for every single user. It would also prevent those without slack accounts from connecting to our IRC.
This could be totally wrong because tanya does not seem to have a lot of documentation, so I'm basing this off the short README and skimming the code.

**Comment by gnowxilef** [comment]
as i mentioned in https://github.com/ocf/ircbot/issues/145, it would only be for ircbot. wasn't clear on that before sorry.

**Comment by gnowxilef** [comment]
i'll close out this issue, since the bridge is different.
